global:
  # -- Default domain used by all components
  ## Used for ingresses, certificates, SSO, notifications, etc.
  domain: argocd.k3d.localhost

  affinity:
      # -- Default pod anti-affinity rules. Either: `none`, `soft` or `hard`
      podAntiAffinity: soft
      # Node affinity rules
      nodeAffinity:
        # -- Default node affinity rules. Either: `none`, `soft` or `hard`
        type: hard
        # -- Default match expressions for node affinity
        matchExpressions:
          - key: node-role.kubernetes.io/control-plane
            operator: In
            values:
            - "true"


server:
  ingress:
    # -- Enable an ingress resource for the Argo CD server
    enabled: true
    pathType: Prefix

configs:
  params:
    server.insecure: true

  cm:
    # URL used by users to access the UI locally
    url: "http://argocd.k3d.localhost:8081"
    
    # Enable native OIDC
    oidc.config: |
      name: Keycloak
      # Use the internal cluster DNS name and internal port (8080)
      issuer: "http://keycloak.k3d.localhost:8081/realms/k3d"
      clientID: "argocd"
      clientSecret: "$argocd-secret:oidc.keycloak.clientSecret"
      requestedScopes: ["openid", "profile", "email", "groups"]
      InsecureSkipVerify: true

  # Map Keycloak groups to Admin permissions within ArgoCD
  rbac:
    policy.csv: |
      g, argocd-admins, role:admin

  # Safely inject the confidential client secret without plain-text exposure
  secret:
    extra:
      # Tell the Helm chart to merge your manual secret into ArgoCD
      secretName: "argocd-secret-extra"

